---
- name: Install docker
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
       
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Docker | Install Docker | Create Docker group
      group:
        name: docker
        state: present

    - name: Docker | Install Docker | Add Docker group to local user
      user:
        name: ubuntu
        comment: "add user to docker group"
        groups: docker
        append: yes
      become: true
      become_method: sudo

    - name: Docker | Install Docker | Enable Docker service at boot
      service:
        name: docker
        enabled: yes
        state: restarted
      become: true
      become_method: sudo

   - name: Change default cgroup driver to systemd
      blockinfile:
        path: /etc/docker/daemon.json
        block: |
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
     become: true