apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  labels:
    run: jenkins
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: jenkins
  type: LoadBalancer